### Homework - 16

In [8]:
"""1. Convert List to 1D Array
 Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]"""
import numpy

my_list = [34, 56, 78, 99]

my_array = numpy.array(my_list)

print(my_array)

[34 56 78 99]


In [14]:
"""2. Create 3x3 Matrix (2?10)
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4] [ 5 6 7] [ 8 9 10]]"""

import numpy

my_list2 = [[2, 3, 4], [5, 6, 7], [8, 9, 10]]

matrix = numpy.array(my_list2)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [20]:
"""3. Null Vector (10) & Update Sixth Value
Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]"""

import numpy as np

null_vector = np.zeros(10)
null_vector[6] = 11

print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [57]:
"""4. Array from 12 to 38
Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]"""

import numpy as np

range_4 = range(12, 38)

#for i in range_4:
  #  print(i)

my_array4 = np.array(range_4)

print(my_array4)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [53]:
"""5. Convert Array to Float Type
Write a NumPy program to convert an array to a floating type.

Sample output:

Original array [1, 2, 3, 4]"""

import numpy

my_array5 = np.array([1, 2, 3, 4])

my_array5.astype(float)

array([1., 2., 3., 4.])

In [118]:
"""6. Celsius to Fahrenheit Conversion
Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]
"""
import numpy

C = [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
C_array = np.array(C)

print(1.8*C_array + 32)



[-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [ ]:
"""7. Append Values to Array (Do self-tudy)
Write a NumPy program to append values to the end of an array.

Expected Output:

Original array: [10, 20, 30]

After append values to the end of the array: [10 20 30 40 50 60 70 80 90]"""
import numpy

original_array = [10, 20, 30]
new_values = [40, 50, 60, 70, 80, 90]

original_array_1 = np.array(original_array)

numpy.append(original_array_1, new_values, axis=None )


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
"""8. Array Statistical Functions (Do self-tudy)
Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array."""
import math
from numpy import random
random_8 = random.randint(100, size=(10))

print(random_8)
print(random_8.mean())
print((random_8[4]+random_8[5])/2)

variance = sum((random_8 - random_8.mean())**2)/10
print(math.sqrt(variance))

[94 78 70 85  2 45 42 24 78 27]
54.5
23.5
29.196746394076175


In [41]:
"""9 Find min and max
Create a 10x10 array with random values and find the minimum and maximum values."""

from numpy import random

random_values = random.rand(10,10)

print(random_values)

print(random_values.max())

print(random_values.min())

[[0.01087317 0.33885754 0.8538328  0.98709638 0.25128668 0.80091058
  0.47995422 0.67583    0.18852638 0.44893955]
 [0.9375994  0.70513663 0.8387356  0.47596676 0.14527232 0.83003375
  0.1867471  0.50886908 0.38200537 0.35913076]
 [0.7211761  0.01271275 0.23850094 0.89369136 0.99751131 0.34490668
  0.97309429 0.86414304 0.88042609 0.97876361]
 [0.4883256  0.67155199 0.43365224 0.30770701 0.52442162 0.07864539
  0.10482508 0.36665392 0.96045821 0.886388  ]
 [0.79939995 0.9629281  0.86056293 0.18165871 0.01814089 0.53511105
  0.12239323 0.72567514 0.43066849 0.22819146]
 [0.41852276 0.9516753  0.37416334 0.03937392 0.93660535 0.33773294
  0.58245907 0.0490904  0.9221212  0.18043409]
 [0.93904132 0.66138975 0.99224326 0.96004666 0.91975638 0.40718322
  0.98967815 0.35728629 0.16130054 0.63178094]
 [0.20471935 0.2402719  0.22174402 0.45892371 0.92111175 0.91319938
  0.73006631 0.01174012 0.67699069 0.21582154]
 [0.71752532 0.0605317  0.82139018 0.86565534 0.81787191 0.14586425
  0.50973463

In [46]:
"""10
Create a 3x3x3 array with random values."""

from numpy import random

my_array10 = random.rand(3,3,3)

my_array10

array([[[0.76334282, 0.36040422, 0.19570868],
        [0.7503266 , 0.44412171, 0.63546559],
        [0.62404701, 0.71271615, 0.68819623]],

       [[0.8743767 , 0.38755681, 0.96247722],
        [0.05308446, 0.97026142, 0.36489895],
        [0.26564477, 0.76259181, 0.80151411]],

       [[0.26221969, 0.14190884, 0.08159197],
        [0.21428549, 0.81435615, 0.04352771],
        [0.59217285, 0.2070616 , 0.16287613]]])